.TH MML2MID 1 "2001年2月1日"
.SH NAME 名称
mml2mid \- MML言語で書かれた音楽ファイルをMIDIファイルにコンパイル
.SH SYNOPSIS 形式
.B mml2mid
[
.B \-fxvmwc
] [
.B \-t
.I NUM
]
.I FILENAME\c
[.mml] [\c
.I FILENAME\c
.BR "" .mid]

.SH DESCRIPTION 概説
.RB "  " mml2mid
は、MML言語で書かれた音楽ファイルを標準MIDIファイル(SMF)にコンパイルする。
.br
  当マニュアルで説明するのは、
.B mml2mid
コマンドを起動する際の書式だけである。MMLファイルの文法については、
.B mml2mid
に別途添付のドキュメント「mml2mid 利用の手引」(doc/mml2mid.txt)を
参照のこと。また、当マニュアルが対象とするのは、
UNIX版/Win32コンソール版/DOS版の
.B mml2mid
だけであり、Windows GUI版については
述べていない。

.RB "  " mml2mid
の引数のうち「\-」で始まるもの(但し「\-」1文字
だけのものを除く。以下も同様)は、
後述するオプション引数と見なされる。
.B mml2mid
は、与えられた引数を先頭から
調べていき、「\-」で始まらないものが
最初に現れた時点で、それを入力MMLファイル名と
解釈する。入力MMLファイル名が与えられていなければエラー終了となる。
.br
  さらに、その次以降の引数で「\-」で始まらないものがもしあれば、
そのうち最初に現れたものを、出力MIDIファイル名と
解釈する(それが「.mid」で終わっていなくても、その名前の
ファイルに出力される)。なければ、入力MMLファイル名の拡張子を「\c
.B .mid\c
」に変えたもの(但し、入力MMLファイル名に拡張子がなければその後ろに「\c
.B .mid\c
」を付けたもの)が出力MIDIファイル名となる。
.br
  出力MIDIファイル名と解釈された引数がある場合、
それ以後の引数は全て、オプション引数でなければ(つまり「\-」で
始まっていなければ)ならない。

  入力MMLファイル名と解釈された引数が「\-」であった
場合、標準入力を読み込む(bccでコンパイルされたDOS版を
除く)。またこの場合、出力MIDIファイル名が
指定されていなければ、MIDI出力は標準出力に出る(UNIX版のみ)。
但し、端末へは出力できず、ファイルかパイプへリダイレクトせねばならない。
.br
  また、出力MIDIファイル名と解釈された引数が「\-」で
あった場合も、MIDI出力は標準出力に出る(UNIX版のみ)。

.SH オプション OPTIONS
  上述のように、オプション引数はファイル名引数の
前にも後にも指定できる。また、
例えば「\-v \-m \-t 2」の代わりに「\-vmt2」のようにまとめて
指定したりもできるようになっており、これはC言語ライブラリの
.B getopt\c
(3)関数と同様の動作になっている。
.br
  オプション引数には以下のようなものがある。
.\"なおDOS版では、オプションは大文字で指定してもよい。
.TP
.B \-f
FORMAT 0のMIDIファイルを出力する。デフォルトではFORMAT 1。
.TP
.B \-x
MMLファイル中のオクターブの上げ下げの記号(「<」「>」)を逆の意味にする。
.TP
.B \-v
MMLファイル中のベロシティの上げ下げの記号(「(」「)」)を逆の意味にする。
.TP
.B \-m
MMLファイル中で、文字列のコードとしてMS漢字コード(シフトJIS)を
仮定するかどうかを反転させる。デフォルトでは、UNIX版ではMS漢字コード
を仮定せず、DOS版では仮定する。間違った仮定を行うと、正常なコンパイルが
できない場合がある。
.TP
.B \-w
MMLファイル中に理解できない文字が
現れた場合、エラー終了せずに、警告だけ出してその
文字を無視し、コンパイルを続ける。
.TP
.B \-c
古いバージョンの
.B mml2mid
に存在した、ドキュメントに書かれていなかった振る舞いを
模倣する。すなわち、MMLファイル中の、
行頭が空白の行は注釈行と見なし(前の行からの継続行は
除く)、また、「/* */」による空白が閉じていなくてもエラーと
しない。このオプションの使用は推奨しない。
.TP
.BI \-t " NUM"
全体を半音のNUM倍だけ移調する(NUMが正の場合に高い方へ
移調)。NUMは\-24〜24の整数でなければならない。
.PP
  このうち
.B \-t
を除く各オプションは実はトグル・スイッチになっており、
偶数回指定すると元に戻る。

.SH 環境変数 ENVIRONMENT VARIABLES
  環境変数
.B MML2MID_OPTIONS
が指定されていると、その値が、
.B mml2mid
の起動時にコマンドラインオプションとして付加される。

.SH 診断 DIAGNOSTICS
  正常にコンパイルが終了した場合0、何らかのエラーの
場合(指定ファイルがオープンできない、MMLファイルの
文法エラー、など)は非0を返す。

.SH 例 EXAMPLES
.TP
mml2mid sample.mml output.mid
  MMLファイルsample.mmlをMIDIファイルoutput.midに変換。
.TP
mml2mid \-mft4 sample.mml
  MMLファイルsample.mmlを、4半音高く移調
してFORMAT 0のMIDIファイルsample.midに
変換。MMLファイル中の文字列は、デフォルトとは
逆に、UNIXではMS漢字コードと解釈され、DOSではMS漢字コードで
ないと解釈される。「mml2mid \-m \-f \-t4 sample.mml」や
「mml2mid sample.mml \-m \-f \-t4」などでも同じ。
